### ISSUE TITLE
ImportError: No module named unicodedata

### ISSUE THREAD

**Issue by Scottie313** [d0ugal/RstPreview#1]
Hi!
After installing your plugin, I get following error message:

``` python
Reloading plugin D:\Tools\SublimeText2\Data\Packages\RstPreview\RstPreview.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\RstPreview.py", line 11, in <module>
    from docutils.core import publish_string
  File ".\docutils\core.py", line 20, in <module>
    from docutils import frontend, io, utils, readers, writers
  File ".\docutils\frontend.py", line 39, in <module>
    import docutils.utils
  File ".\docutils\utils\__init__.py", line 16, in <module>
    import unicodedata
ImportError: No module named unicodedata
```

But if I manually import the unicodedata module by issuing the command:

``` python
>>> import unicodedata
```

then there is no error.

**Comment by d0ugal** [comment]
@Scottie313 thanks for the report.

I only just wrote this the other day. It was working fine but something seems to have gone wrong with the bundled version of docutils. I've not yet managed to figure out why yet or had the time to look properly.

**Comment by d0ugal** [comment]
This was fixed in 7be1ae6e3f. There is now an extra installation step though, so be sure to check the readme.

**Comment by Scottie313** [comment]
Many Thanks! It's much better than before, but in my case it was not easy. Maybe because I have a portable version of the Sublime Text 2. Anyway...

First, when I set:

```
PYTHONPATH=C:\Python\Python27\Lib;C:\Python\Python27\Lib\site-packages
```

and enven set:

```
"env":
{
    "PATH": "C:\\Python\\Python27;c:\\Python\\Python27\\Scripts",
    "PYTHONPATH": "C:\\Python\\Python27\\Lib;C:\\Python\\Python27\\Lib\\site-packages;C:\\Python\\Python27\\DLLs"
}
```

in the my "Preferences.sublime-settings" file, the docutils package was not visible and did not want to import in ST2:

```
>>> import docutils
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named docutils
```

**Only when I added the following commands:**

``` python
sys.path.append("C:\\Python\\Python27\\Lib")
sys.path.append("C:\\Python\\Python27\\Lib\\site-packages")
```

**then your package has started to work properly.**

Maybe there is a simpler way to configure and set PYTHONPATH to be visible in Sublime Text 2, but I don't know it.

Best regards,<br />--<br />Scottie

**Comment by d0ugal** [comment]
Aha, I hadn't considered the portable version of sublime text. Also, perhaps sublime for windows ships with its own python install. That would make sense since windows doesn't have python by default.

Unfortunately I don't use windows, so it's hard for me to guide further. However, I'm going to re-open this issue so others might see this and maybe somebody else can help out.

**Comment by d0ugal** [comment]
Actually, to keep things clear, I opened a new issue that explains this problem, #7.
