### ISSUE TITLE
"no command for selector: noop:" error

### ISSUE THREAD

**Issue by askaliuk** [d0ugal/RstPreview#16]
Hello,
Tried to use your plugin on OSX 10.8.2 (Sublime 2.0.1)
When i try to run preview Sublime console output is:

``` text
no command for selector: noop:
```

docutils import works ok.
Thanks for help.

**Comment by d0ugal** [comment]
Hi,

Sorry, I didn't spot this issue when you originally opened it.

I've never seen this error - are you still having problems? If your still interested in making it work I can try to help.

**Comment by askaliuk** [comment]
Looks like i can't repeat it anymore. Thank you for help.
