### ISSUE TITLE
ImportError: No module named standalone

### ISSUE THREAD

**Issue by mattfarina** [d0ugal/RstPreview#2]
I installed this package and get the following error when I try to use it. I'm on OS X Lion.

Traceback (most recent call last):
  File "/Applications/Sublime Text 2.app/Contents/MacOS/sublime_plugin.py", line 362, in run_
    return self.run(edit)
  File "./RstPreview.py", line 46, in run
  File "./docutils/core.py", line 418, in publish_string
  File "./docutils/core.py", line 661, in publish_programmatically
  File "./docutils/core.py", line 93, in set_components
  File "./docutils/core.py", line 82, in set_reader
  File "./docutils/readers/**init**.py", line 106, in get_reader_class
ImportError: No module named standalone

**Comment by d0ugal** [comment]
I'm afraid this is related to #1. I've not been able to resolve it yet, there is an issue with bundling docutils in the plugin. Any help or suggestions welcome :)

**Comment by mattfarina** [comment]
What setup to you have to make this work?

**Comment by d0ugal** [comment]
I'm on OSX Lion too.

So the strange thing is that when I'm hacking on the plugin and editing it and its loaded into SLT2 it works fine. It's only when I re-start SLT2 that it seems to stop working. This is why I thought it was working for a while but now I've given up. I think there may be something odd/different regarding the SLT2 Python environment that I don't understand.

**Comment by mattfarina** [comment]
This is quite strange. If I work on the plugin I can get it to work... that is until i restart ST2. Then it fails. I'm not a python guy and am not sure what's going on.

**Comment by d0ugal** [comment]
Yup, sounds like you got into the same situation as me. I **am** a Python guy and I'm still very confused :(

**Comment by d0ugal** [comment]
This was fixed in 7be1ae6e3f. There is now an extra installation step though, so be sure to check the readme.
